# Generated by Django 5.2.1 on 2025-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('personal_belongings', 'Personal Belongings'), ('bags_accessories', 'Bags and Accessories'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('clothing_wearables', 'Clothing and Wearables'), ('kids_items', "Kids' Items"), ('pets', 'Pets'), ('vehicles_related', 'Vehicles and Related Items'), ('office_study', 'Office and Study Items'), ('religious_items', 'Religious Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('personal_belongings', 'Personal Belongings'), ('bags_accessories', 'Bags and Accessories'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('clothing_wearables', 'Clothing and Wearables'), ('kids_items', "Kids' Items"), ('pets', 'Pets'), ('vehicles_related', 'Vehicles and Related Items'), ('office_study', 'Office and Study Items'), ('religious_items', 'Religious Items')], max_length=50),
        ),
    ]
