# Generated by Django 5.2.1 on 2025-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_my_reg_groups_my_reg_is_active_my_reg_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_reg',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
