# Generated by Django 5.2.1 on 2025-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_lostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
