# Generated by Django 5.2.1 on 2025-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_lostitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
