# Generated by Django 5.2.1 on 2025-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_reg',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
