# Generated by Django 5.2.2 on 2025-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_my_reg_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_reg',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='my_reg',
            name='otp',
            field=models.CharField(blank=True, default='000000', max_length=6, null=True),
        ),
    ]
