# Generated by Django 5.2.4 on 2025-07-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categeory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categeory',
        ),
        migrations.AddField(
            model_name='claimitem',
            name='found_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.founditem'),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='lost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lostitem'),
        ),
    ]
